from .nodes import NODE_CLASS_MAPPINGS as NODES_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NODES_DISPLAY_NAME_MAPPINGS
from .voice_presets import NODE_CLASS_MAPPINGS as PRESETS_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PRESETS_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**NODES_CLASS_MAPPINGS, **PRESETS_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**NODES_DISPLAY_NAME_MAPPINGS, **PRESETS_DISPLAY_NAME_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
